version: '3.5'

services:
  library-db:
    container_name: library-db
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: library
    volumes:
      - postgres-db:/data/postgres
    ports:
      - "5455:5432"

volumes:
  postgres-db:
    driver: local